### ISSUE TITLE
Can't install the npm module

### ISSUE THREAD

**Issue by troglodisme** [tuna-f1sh/node-flipdot#5]
Has anybody tested this recently? I am trying to install the nodule but getting maaaany errors, copying the beginning part here below. Thanks.

`giulio@Giulios-MacBook-Air ~ % npm install flipdot-display
npm ERR! code 1
npm ERR! path /Users/giulio/node_modules/flipdot-display/node_modules/serialport
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build
npm ERR! CXX(target) Release/obj.target/serialport/src/serialport.o
npm ERR!   CXX(target) Release/obj.target/serialport/src/serialport.o
npm ERR! Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/giulio/node_modules/flipdot-display/node_modules/serialport/build/Release/serialport.node --module_name=serialport --module_path=/Users/giulio/node_modules/flipdot-display/node_modules/serialport/build/Release' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@0.6.36
npm ERR! node-pre-gyp info using node@16.15.0 | darwin | arm64
npm ERR! node-pre-gyp info check checked for "/Users/giulio/node_modules/flipdot-display/node_modules/serialport/build/Release/serialport.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/5.0.0/serialport-v5.0.0-node-v93-darwin-arm64.tar.gz
npm ERR! node-pre-gyp http 404 https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/5.0.0/serialport-v5.0.0-node-v93-darwin-arm64.tar.gz
npm ERR! node-pre-gyp ERR! Tried to download(404): https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/5.0.0/serialport-v5.0.0-node-v93-darwin-arm64.tar.gz 
npm ERR! node-pre-gyp ERR! Pre-built binaries not found for serialport@5.0.0 and node@16.15.0 (node-v93 ABI) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp http 404 status code downloading tarball https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/5.0.0/serialport-v5.0.0-node-v93-darwin-arm64.tar.gz 
npm ERR! node-pre-gyp ERR! Tried to download(undefined): https://github.com/EmergingTechnologyAdvisors/node-serialport/releases/download/5.0.0/serialport-v5.0.0-node-v93-darwin-arm64.tar.gz 
npm ERR! node-pre-gyp ERR! Pre-built binaries not found for serialport@5.0.0 and node@16.15.0 (node-v93 ABI) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp http Connection closed while downloading tarball file 
npm ERR! gypgyp info it worked if it ends with  ok
npm ERR! info it worked if it ends with ok
npm ERR! gypgyp  infoinfo  usingusing node-gyp@9.0.0
npm ERR!  node-gyp@9.0.0
npm ERR! gypgyp  info infousing using node@16.15.0 | darwin | arm64
npm ERR!  node@16.15.0 | darwin | arm64
npm ERR! gypgyp info  info okok 
npm ERR!  
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@16.15.0 | darwin | arm64
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@16.15.0 | darwin | arm64
npm ERR! gypgyp  info info find Pythonfind Python using Python version 3.8.9 found at "/Applications/Xcode.app/Contents/Developer/usr/bin/python3"
npm ERR!  using Python version 3.8.9 found at "/Applications/Xcode.app/Contents/Developer/usr/bin/python3"
npm ERR! gypgyp info spawn /Applications/Xcode.app/Contents/Developer/usr/bin/python3
npm ERR!  infogyp  spawn /Applications/Xcode.app/Contents/Developer/usr/bin/python3
npm ERR! info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/giulio/node_modules/flipdot-display/node_modules/serialport/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/giulio/Library/Caches/node-gyp/16.15.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/giulio/Library/Caches/node-gyp/16.15.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/giulio/Library/Caches/node-gyp/16.15.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/giulio/node_modules/flipdot-display/node_modules/serialport',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gypgyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR!  info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/giulio/node_modules/flipdot-display/node_modules/serialport/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/giulio/Library/Caches/node-gyp/16.15.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/giulio/Library/Caches/node-gyp/16.15.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/giulio/Library/Caches/node-gyp/16.15.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/giulio/node_modules/flipdot-display/node_modules/serialport',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gypgyp info ok 
npm ERR!  info ok 
npm ERR! gyp info it worked if it en`

**Comment by tuna-f1sh** [comment]
It’s been a while time since I’ve used it. Quick glance here: it looks like the node-serial port module is failing to compile - possibly because it’s arm64? If this is on a RPi, you could try a 32 bit Raspbian.

Otherwise, all the modules need bringing up to date. I wouldn’t expect this to work without some changes however as it’s been 4+ years.

**Comment by tuna-f1sh** [comment]
I’ve pushed an update that bumps node-serial port a few versions until it compiles. Not tested with physical port but seems to work…

Will publish new version on npm once I’ve tested it.

**Comment by simonprickett** [comment]
Thanks - I've just hit the same while trying this on a Mac.  Can go try on a Pi too.  Also thanks for the video and writeup.

**Comment by tuna-f1sh** [comment]
Cool. I've published 1.2.0 now having tested the serial port still works. If you install this version it should fix the issue.

**Comment by simonprickett** [comment]
Thanks will try it out this week - got to figure out my RS485 wiring first... my USB to RS385 has A, B, GND... guessing the red and black wires from the sign go to A and GND and B is redundant, but seeing all sorts of conflicting information.  If I get something up and running will share my project - I have a 87x7 sign.

**Comment by tuna-f1sh** [comment]
@simonprickett - guessed wrong! RS485 is like RS232 but differential; A is positive and B is negative. I can't say for sure what colour is which but RED is probably A and BLACK B. It won't break anything to miss-wire them so if it doesn't work, try swapping them. GND is actually the one that can be considered redundant, but best to connect it anyway (to GND with display supply).

**Comment by simonprickett** [comment]
I'll keep puzzling through mine but the software installs fine (Mac OS Monterey) and the sign is set to address 0 and I have my black wire connected to B on the USB->RS485 and the red to A, but getting nothing on the sign when I try this:

```
$ flipdot --address 0 --c 7 --r 84 --p /dev/tty.usbserial-14130
FlipDot port open on /dev/tty.usbserial-14130 @: 4800
Sending: Hello World!!
Writing...
Written!
```

It takes a long time between Writing and Written.  I have two data cables for the sign, one with an arrow pointing into a box (I assume this is the one to connect to) and one with an arrow pointing away from a box (I assume this is to chain the next display onto).  I've also seen there's a set of pins in the sign marked LK3 that have jumpers... my sign had jumpers set on the B and C positions. If I remove these and restart the power to the sign with a jumper in position E I get a self-test on the sigh.  

Trying to work out the right combination of RS485 wires, which pair of wires it is, and whether the jumpers play a part in this... hopefully I will get there but no luck sending data to the sign so far.

**Comment by tuna-f1sh** [comment]
Double check you have the correct address for the display (or try all addresses) and also the correct aspect ratio. 

I'll close this now though since the installing issue is fixed.

**Comment by simonprickett** [comment]
thank you!
